
;--- Generated .INC file by COMView
;--- typelib name=COMlibiconvc
;--- documentation=COMlibiconv Library
;--- GUID={55B7D56A-C63A-4B39-9833-A2925972CA96}
;--- Version 1.0, LCID 0

;--- prototypes too complex for MASM may exist
;--- if such ones reside in a vtable they will be replaced by dummies
;--- search for occurances of ';+++' to have a closer look at these

;--- here dispatchonly interfaces are described
;--- whose methods/properties can be accessed thru IDispatch::Invoke only
;--- use macro dm() to call a method/property of such an interface.
;--- macro dm(), which is described in file objbase.inc,
;--- requires placing macro DEFINE_INVOKEHELPER somewhere in your source code

;--- end of type library ---
